import FooterComponent from "@/components/footer";
import HeaderComponent from "@/components/header";
import { Metadata } from "next/types";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bruno Truong",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <HeaderComponent />
          {children}
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
